# 后端基础信息
spring:
  application:
    name: learning-compass-backend
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # mysql 数据库连接配置
  datasource:
    url: jdbc:mysql://localhost:3306/learning_compass?useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
  # 文件上传限制
  servlet:
    multipart:
      max-file-size: 10MB
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
# 后端服务器设置
server:
  address: 0.0.0.0
  port: 8080
  servlet:
    context-path: /api
# mybatis-plus设置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete    # 全局逻辑删除的实体字段名
      logic-delete-value: 1  # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0   # 逻辑未删除值(默认为 0)
############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: learningcompass
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true
# 接口文档配置
knife4j:
  enable: true
  setting:
    language: en
  openapi:
    title: "Learning Compass API Documentation"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.ice.learningcompass.controller